# Generated by Django 4.2.7 on 2024-10-17 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Category_English_name",
                    models.CharField(max_length=250, unique=True),
                ),
                ("Category_Arabic_name", models.CharField(max_length=250, unique=True)),
                ("categoryslug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="Categories"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "english_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "arabic_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "subcategory",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "imgSrc",
                    models.ImageField(blank=True, null=True, upload_to="Categories"),
                ),
                ("content", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="telegram.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Articles",
            },
        ),
    ]
