# Generated by Django 4.2.7 on 2024-10-17 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="categoryslug",
            new_name="Category_slug",
        ),
    ]
